name: R2 Bucket Sync

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Simple manual trigger with no parameters

jobs:
  sync-r2-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install AWS CLI
        run: |
          if ! command -v aws &> /dev/null; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          
      - name: Configure AWS CLI for R2
        run: |
          # Configure AWS CLI to use R2 credentials directly
          aws configure set aws_access_key_id ${{ secrets.R2_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws configure set endpoint_url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          aws configure set region auto
          
      - name: Sync files to R2
        run: |
          # Sync repository content to R2 while excluding .git directory and patterns from .gitignore
          aws s3 sync ./ s3://${{ secrets.R2_BUCKET_NAME }} \
            --exclude ".git/*" \
            --exclude ".git" \
            --exclude ".github/*" \
            --exclude ".obsidian/*" \
            --exclude "logseq/*" \
            --exclude ".gitignore" \
            --exclude ".claude/*" \
            --delete
          
